apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
      - name: hello
        image: 968423163201.dkr.ecr.us-east-1.amazonaws.com/hello:latest
        ports:
        - containerPort: 80
# vf vf 
# sai
